Updating build index: /Users/runner/conda/conda-bld

TEST START: dropbox-11.18.0-pyhd8ed1ab_0.tar.bz2
Mamba failed to solve:
 - dropbox 11.18.0 pyhd8ed1ab_0
 - python =2.7|>=3.4
 - requests >=2.16.2
 - six >=1.12.0
 - stone >=2
 - pytest-mock
 - coverage
 - pip
 - mock
 - python

with channels:
 - file:///Users/runner/conda/conda-bld

The reported errors are:
   Encountered problems while solving:
     - nothing provides __unix needed by stone-3.2.1-pyhd8ed1ab_0
     - nothing provides __unix needed by stone-3.2.1-pyhd8ed1ab_0
   

Leaving build/test directories:
  Work:
 /Users/runner/conda/conda-bld/work 
  Test:
 /Users/runner/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /Users/runner/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla 
  Build:
source activate  /Users/runner/conda/conda-bld/_build_env 


